name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
      - name: Install pnpm
        run: corepack enable pnpm
      - name: Install dependencies
        run: pnpm i
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build
      - name: ensure no outstanding migrations
        run: | 
          pnpm db:generate && \
          if [ -z "$(git status --porcelain)" ]; then \
            exit 0; \
          else \
            exit 1; \
          fi
